/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * AggregateIndicators
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class AggregateIndicators {
  @SerializedName("technicalAnalysis")
  private TechnicalAnalysis technicalAnalysis = null;

  @SerializedName("trend")
  private Trend trend = null;

  public AggregateIndicators technicalAnalysis(TechnicalAnalysis technicalAnalysis) {
    this.technicalAnalysis = technicalAnalysis;
    return this;
  }

   /**
   * Get technicalAnalysis
   * @return technicalAnalysis
  **/
  @Schema(description = "")
  public TechnicalAnalysis getTechnicalAnalysis() {
    return technicalAnalysis;
  }

  public void setTechnicalAnalysis(TechnicalAnalysis technicalAnalysis) {
    this.technicalAnalysis = technicalAnalysis;
  }

  public AggregateIndicators trend(Trend trend) {
    this.trend = trend;
    return this;
  }

   /**
   * Get trend
   * @return trend
  **/
  @Schema(description = "")
  public Trend getTrend() {
    return trend;
  }

  public void setTrend(Trend trend) {
    this.trend = trend;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregateIndicators aggregateIndicators = (AggregateIndicators) o;
    return Objects.equals(this.technicalAnalysis, aggregateIndicators.technicalAnalysis) &&
        Objects.equals(this.trend, aggregateIndicators.trend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(technicalAnalysis, trend);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregateIndicators {\n");
    
    sb.append("    technicalAnalysis: ").append(toIndentedString(technicalAnalysis)).append("\n");
    sb.append("    trend: ").append(toIndentedString(trend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
