/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * BondCandles
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class BondCandles {
  @SerializedName("c")
  private List<Float> c = null;

  @SerializedName("t")
  private List<Long> t = null;

  @SerializedName("s")
  private String s = null;

  public BondCandles c(List<Float> c) {
    this.c = c;
    return this;
  }

  public BondCandles addCItem(Float cItem) {
    if (this.c == null) {
      this.c = new ArrayList<Float>();
    }
    this.c.add(cItem);
    return this;
  }

   /**
   * List of close prices for returned candles.
   * @return c
  **/
  @Schema(description = "List of close prices for returned candles.")
  public List<Float> getC() {
    return c;
  }

  public void setC(List<Float> c) {
    this.c = c;
  }

  public BondCandles t(List<Long> t) {
    this.t = t;
    return this;
  }

  public BondCandles addTItem(Long tItem) {
    if (this.t == null) {
      this.t = new ArrayList<Long>();
    }
    this.t.add(tItem);
    return this;
  }

   /**
   * List of timestamp for returned candles.
   * @return t
  **/
  @Schema(description = "List of timestamp for returned candles.")
  public List<Long> getT() {
    return t;
  }

  public void setT(List<Long> t) {
    this.t = t;
  }

  public BondCandles s(String s) {
    this.s = s;
    return this;
  }

   /**
   * Status of the response. This field can either be ok or no_data.
   * @return s
  **/
  @Schema(description = "Status of the response. This field can either be ok or no_data.")
  public String getS() {
    return s;
  }

  public void setS(String s) {
    this.s = s;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BondCandles bondCandles = (BondCandles) o;
    return Objects.equals(this.c, bondCandles.c) &&
        Objects.equals(this.t, bondCandles.t) &&
        Objects.equals(this.s, bondCandles.s);
  }

  @Override
  public int hashCode() {
    return Objects.hash(c, t, s);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BondCandles {\n");
    
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
