/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CompanyNewsStatistics
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class CompanyNewsStatistics {
  @SerializedName("articlesInLastWeek")
  private Long articlesInLastWeek = null;

  @SerializedName("buzz")
  private Float buzz = null;

  @SerializedName("weeklyAverage")
  private Float weeklyAverage = null;

  public CompanyNewsStatistics articlesInLastWeek(Long articlesInLastWeek) {
    this.articlesInLastWeek = articlesInLastWeek;
    return this;
  }

   /**
   * Get articlesInLastWeek
   * @return articlesInLastWeek
  **/
  @Schema(description = "")
  public Long getArticlesInLastWeek() {
    return articlesInLastWeek;
  }

  public void setArticlesInLastWeek(Long articlesInLastWeek) {
    this.articlesInLastWeek = articlesInLastWeek;
  }

  public CompanyNewsStatistics buzz(Float buzz) {
    this.buzz = buzz;
    return this;
  }

   /**
   * Get buzz
   * @return buzz
  **/
  @Schema(description = "")
  public Float getBuzz() {
    return buzz;
  }

  public void setBuzz(Float buzz) {
    this.buzz = buzz;
  }

  public CompanyNewsStatistics weeklyAverage(Float weeklyAverage) {
    this.weeklyAverage = weeklyAverage;
    return this;
  }

   /**
   * Get weeklyAverage
   * @return weeklyAverage
  **/
  @Schema(description = "")
  public Float getWeeklyAverage() {
    return weeklyAverage;
  }

  public void setWeeklyAverage(Float weeklyAverage) {
    this.weeklyAverage = weeklyAverage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyNewsStatistics companyNewsStatistics = (CompanyNewsStatistics) o;
    return Objects.equals(this.articlesInLastWeek, companyNewsStatistics.articlesInLastWeek) &&
        Objects.equals(this.buzz, companyNewsStatistics.buzz) &&
        Objects.equals(this.weeklyAverage, companyNewsStatistics.weeklyAverage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articlesInLastWeek, buzz, weeklyAverage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyNewsStatistics {\n");
    
    sb.append("    articlesInLastWeek: ").append(toIndentedString(articlesInLastWeek)).append("\n");
    sb.append("    buzz: ").append(toIndentedString(buzz)).append("\n");
    sb.append("    weeklyAverage: ").append(toIndentedString(weeklyAverage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
