/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.LocalDate;
/**
 * CompanyProfile2
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class CompanyProfile2 {
  @SerializedName("country")
  private String country = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("exchange")
  private String exchange = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ticker")
  private String ticker = null;

  @SerializedName("ipo")
  private String ipo = null;

  @SerializedName("marketCapitalization")
  private Float marketCapitalization = null;

  @SerializedName("shareOutstanding")
  private Float shareOutstanding = null;

  @SerializedName("logo")
  private String logo = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("weburl")
  private String weburl = null;

  @SerializedName("finnhubIndustry")
  private String finnhubIndustry = null;

  public CompanyProfile2 country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country of company&#x27;s headquarter.
   * @return country
  **/
  @Schema(description = "Country of company's headquarter.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CompanyProfile2 currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency used in company filings.
   * @return currency
  **/
  @Schema(description = "Currency used in company filings.")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public CompanyProfile2 exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Listed exchange.
   * @return exchange
  **/
  @Schema(description = "Listed exchange.")
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public CompanyProfile2 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Company name.
   * @return name
  **/
  @Schema(description = "Company name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CompanyProfile2 ticker(String ticker) {
    this.ticker = ticker;
    return this;
  }

   /**
   * Company symbol/ticker as used on the listed exchange.
   * @return ticker
  **/
  @Schema(description = "Company symbol/ticker as used on the listed exchange.")
  public String getTicker() {
    return ticker;
  }

  public void setTicker(String ticker) {
    this.ticker = ticker;
  }

  public CompanyProfile2 ipo(String ipo) {
    this.ipo = ipo;
    return this;
  }

   /**
   * IPO date.
   * @return ipo
  **/
  @Schema(description = "IPO date.")
  public String getIpo() {
    return ipo;
  }

  public void setIpo(String ipo) {
    this.ipo = ipo;
  }

  public CompanyProfile2 marketCapitalization(Float marketCapitalization) {
    this.marketCapitalization = marketCapitalization;
    return this;
  }

   /**
   * Market Capitalization.
   * @return marketCapitalization
  **/
  @Schema(description = "Market Capitalization.")
  public Float getMarketCapitalization() {
    return marketCapitalization;
  }

  public void setMarketCapitalization(Float marketCapitalization) {
    this.marketCapitalization = marketCapitalization;
  }

  public CompanyProfile2 shareOutstanding(Float shareOutstanding) {
    this.shareOutstanding = shareOutstanding;
    return this;
  }

   /**
   * Number of oustanding shares.
   * @return shareOutstanding
  **/
  @Schema(description = "Number of oustanding shares.")
  public Float getShareOutstanding() {
    return shareOutstanding;
  }

  public void setShareOutstanding(Float shareOutstanding) {
    this.shareOutstanding = shareOutstanding;
  }

  public CompanyProfile2 logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Logo image.
   * @return logo
  **/
  @Schema(description = "Logo image.")
  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public CompanyProfile2 phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Company phone number.
   * @return phone
  **/
  @Schema(description = "Company phone number.")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public CompanyProfile2 weburl(String weburl) {
    this.weburl = weburl;
    return this;
  }

   /**
   * Company website.
   * @return weburl
  **/
  @Schema(description = "Company website.")
  public String getWeburl() {
    return weburl;
  }

  public void setWeburl(String weburl) {
    this.weburl = weburl;
  }

  public CompanyProfile2 finnhubIndustry(String finnhubIndustry) {
    this.finnhubIndustry = finnhubIndustry;
    return this;
  }

   /**
   * Finnhub industry classification.
   * @return finnhubIndustry
  **/
  @Schema(description = "Finnhub industry classification.")
  public String getFinnhubIndustry() {
    return finnhubIndustry;
  }

  public void setFinnhubIndustry(String finnhubIndustry) {
    this.finnhubIndustry = finnhubIndustry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyProfile2 companyProfile2 = (CompanyProfile2) o;
    return Objects.equals(this.country, companyProfile2.country) &&
        Objects.equals(this.currency, companyProfile2.currency) &&
        Objects.equals(this.exchange, companyProfile2.exchange) &&
        Objects.equals(this.name, companyProfile2.name) &&
        Objects.equals(this.ticker, companyProfile2.ticker) &&
        Objects.equals(this.ipo, companyProfile2.ipo) &&
        Objects.equals(this.marketCapitalization, companyProfile2.marketCapitalization) &&
        Objects.equals(this.shareOutstanding, companyProfile2.shareOutstanding) &&
        Objects.equals(this.logo, companyProfile2.logo) &&
        Objects.equals(this.phone, companyProfile2.phone) &&
        Objects.equals(this.weburl, companyProfile2.weburl) &&
        Objects.equals(this.finnhubIndustry, companyProfile2.finnhubIndustry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, currency, exchange, name, ticker, ipo, marketCapitalization, shareOutstanding, logo, phone, weburl, finnhubIndustry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyProfile2 {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    ipo: ").append(toIndentedString(ipo)).append("\n");
    sb.append("    marketCapitalization: ").append(toIndentedString(marketCapitalization)).append("\n");
    sb.append("    shareOutstanding: ").append(toIndentedString(shareOutstanding)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    weburl: ").append(toIndentedString(weburl)).append("\n");
    sb.append("    finnhubIndustry: ").append(toIndentedString(finnhubIndustry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
