/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Company
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class Company {
  @SerializedName("name")
  private String name = null;

  @SerializedName("age")
  private Long age = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("since")
  private String since = null;

  @SerializedName("sex")
  private String sex = null;

  @SerializedName("compensation")
  private Long compensation = null;

  @SerializedName("currency")
  private String currency = null;

  public Company name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Executive name
   * @return name
  **/
  @Schema(description = "Executive name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Company age(Long age) {
    this.age = age;
    return this;
  }

   /**
   * Age
   * @return age
  **/
  @Schema(description = "Age")
  public Long getAge() {
    return age;
  }

  public void setAge(Long age) {
    this.age = age;
  }

  public Company title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title
   * @return title
  **/
  @Schema(description = "Title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Company since(String since) {
    this.since = since;
    return this;
  }

   /**
   * Year first appointed as executive/director of the company
   * @return since
  **/
  @Schema(description = "Year first appointed as executive/director of the company")
  public String getSince() {
    return since;
  }

  public void setSince(String since) {
    this.since = since;
  }

  public Company sex(String sex) {
    this.sex = sex;
    return this;
  }

   /**
   * Sex
   * @return sex
  **/
  @Schema(description = "Sex")
  public String getSex() {
    return sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  public Company compensation(Long compensation) {
    this.compensation = compensation;
    return this;
  }

   /**
   * Total compensation
   * @return compensation
  **/
  @Schema(description = "Total compensation")
  public Long getCompensation() {
    return compensation;
  }

  public void setCompensation(Long compensation) {
    this.compensation = compensation;
  }

  public Company currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Compensation currency
   * @return currency
  **/
  @Schema(description = "Compensation currency")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Company company = (Company) o;
    return Objects.equals(this.name, company.name) &&
        Objects.equals(this.age, company.age) &&
        Objects.equals(this.title, company.title) &&
        Objects.equals(this.since, company.since) &&
        Objects.equals(this.sex, company.sex) &&
        Objects.equals(this.compensation, company.compensation) &&
        Objects.equals(this.currency, company.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, age, title, since, sex, compensation, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Company {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    since: ").append(toIndentedString(since)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    compensation: ").append(toIndentedString(compensation)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
