/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CongressionalTransaction
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class CongressionalTransaction {
  @SerializedName("amountFrom")
  private Float amountFrom = null;

  @SerializedName("amountTo")
  private Float amountTo = null;

  @SerializedName("assetName")
  private String assetName = null;

  @SerializedName("filingDate")
  private String filingDate = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ownerType")
  private String ownerType = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("transactionDate")
  private String transactionDate = null;

  @SerializedName("transactionType")
  private String transactionType = null;

  public CongressionalTransaction amountFrom(Float amountFrom) {
    this.amountFrom = amountFrom;
    return this;
  }

   /**
   * Transaction amount from.
   * @return amountFrom
  **/
  @Schema(description = "Transaction amount from.")
  public Float getAmountFrom() {
    return amountFrom;
  }

  public void setAmountFrom(Float amountFrom) {
    this.amountFrom = amountFrom;
  }

  public CongressionalTransaction amountTo(Float amountTo) {
    this.amountTo = amountTo;
    return this;
  }

   /**
   * Transaction amount to.
   * @return amountTo
  **/
  @Schema(description = "Transaction amount to.")
  public Float getAmountTo() {
    return amountTo;
  }

  public void setAmountTo(Float amountTo) {
    this.amountTo = amountTo;
  }

  public CongressionalTransaction assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Asset name.
   * @return assetName
  **/
  @Schema(description = "Asset name.")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public CongressionalTransaction filingDate(String filingDate) {
    this.filingDate = filingDate;
    return this;
  }

   /**
   * Filing date.
   * @return filingDate
  **/
  @Schema(description = "Filing date.")
  public String getFilingDate() {
    return filingDate;
  }

  public void setFilingDate(String filingDate) {
    this.filingDate = filingDate;
  }

  public CongressionalTransaction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the representative.
   * @return name
  **/
  @Schema(description = "Name of the representative.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CongressionalTransaction ownerType(String ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Owner Type.
   * @return ownerType
  **/
  @Schema(description = "Owner Type.")
  public String getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(String ownerType) {
    this.ownerType = ownerType;
  }

  public CongressionalTransaction position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Position.
   * @return position
  **/
  @Schema(description = "Position.")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public CongressionalTransaction symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol.
   * @return symbol
  **/
  @Schema(description = "Symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public CongressionalTransaction transactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Transaction date.
   * @return transactionDate
  **/
  @Schema(description = "Transaction date.")
  public String getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
  }

  public CongressionalTransaction transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Transaction type &lt;code&gt;Sale&lt;/code&gt; or &lt;code&gt;Purchase&lt;/code&gt;.
   * @return transactionType
  **/
  @Schema(description = "Transaction type <code>Sale</code> or <code>Purchase</code>.")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CongressionalTransaction congressionalTransaction = (CongressionalTransaction) o;
    return Objects.equals(this.amountFrom, congressionalTransaction.amountFrom) &&
        Objects.equals(this.amountTo, congressionalTransaction.amountTo) &&
        Objects.equals(this.assetName, congressionalTransaction.assetName) &&
        Objects.equals(this.filingDate, congressionalTransaction.filingDate) &&
        Objects.equals(this.name, congressionalTransaction.name) &&
        Objects.equals(this.ownerType, congressionalTransaction.ownerType) &&
        Objects.equals(this.position, congressionalTransaction.position) &&
        Objects.equals(this.symbol, congressionalTransaction.symbol) &&
        Objects.equals(this.transactionDate, congressionalTransaction.transactionDate) &&
        Objects.equals(this.transactionType, congressionalTransaction.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountFrom, amountTo, assetName, filingDate, name, ownerType, position, symbol, transactionDate, transactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CongressionalTransaction {\n");
    
    sb.append("    amountFrom: ").append(toIndentedString(amountFrom)).append("\n");
    sb.append("    amountTo: ").append(toIndentedString(amountTo)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
