/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CryptoSymbol
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class CryptoSymbol {
  @SerializedName("description")
  private String description = null;

  @SerializedName("displaySymbol")
  private String displaySymbol = null;

  @SerializedName("symbol")
  private String symbol = null;

  public CryptoSymbol description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Symbol description
   * @return description
  **/
  @Schema(description = "Symbol description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CryptoSymbol displaySymbol(String displaySymbol) {
    this.displaySymbol = displaySymbol;
    return this;
  }

   /**
   * Display symbol name.
   * @return displaySymbol
  **/
  @Schema(description = "Display symbol name.")
  public String getDisplaySymbol() {
    return displaySymbol;
  }

  public void setDisplaySymbol(String displaySymbol) {
    this.displaySymbol = displaySymbol;
  }

  public CryptoSymbol symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Unique symbol used to identify this symbol used in &lt;code&gt;/crypto/candle&lt;/code&gt; endpoint.
   * @return symbol
  **/
  @Schema(description = "Unique symbol used to identify this symbol used in <code>/crypto/candle</code> endpoint.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CryptoSymbol cryptoSymbol = (CryptoSymbol) o;
    return Objects.equals(this.description, cryptoSymbol.description) &&
        Objects.equals(this.displaySymbol, cryptoSymbol.displaySymbol) &&
        Objects.equals(this.symbol, cryptoSymbol.symbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displaySymbol, symbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CryptoSymbol {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displaySymbol: ").append(toIndentedString(displaySymbol)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
