/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Development
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class Development {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("datetime")
  private String datetime = null;

  @SerializedName("headline")
  private String headline = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("url")
  private String url = null;

  public Development symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Company symbol.
   * @return symbol
  **/
  @Schema(description = "Company symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public Development datetime(String datetime) {
    this.datetime = datetime;
    return this;
  }

   /**
   * Published time in &lt;code&gt;YYYY-MM-DD HH:MM:SS&lt;/code&gt; format.
   * @return datetime
  **/
  @Schema(description = "Published time in <code>YYYY-MM-DD HH:MM:SS</code> format.")
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public Development headline(String headline) {
    this.headline = headline;
    return this;
  }

   /**
   * Development headline.
   * @return headline
  **/
  @Schema(description = "Development headline.")
  public String getHeadline() {
    return headline;
  }

  public void setHeadline(String headline) {
    this.headline = headline;
  }

  public Development description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Development description.
   * @return description
  **/
  @Schema(description = "Development description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Development url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL.
   * @return url
  **/
  @Schema(description = "URL.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Development development = (Development) o;
    return Objects.equals(this.symbol, development.symbol) &&
        Objects.equals(this.datetime, development.datetime) &&
        Objects.equals(this.headline, development.headline) &&
        Objects.equals(this.description, development.description) &&
        Objects.equals(this.url, development.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, datetime, headline, description, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Development {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    headline: ").append(toIndentedString(headline)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
