/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * EarningsCallTranscriptsList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class EarningsCallTranscriptsList {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("transcripts")
  private List<StockTranscripts> transcripts = null;

  public EarningsCallTranscriptsList symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Company symbol.
   * @return symbol
  **/
  @Schema(description = "Company symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public EarningsCallTranscriptsList transcripts(List<StockTranscripts> transcripts) {
    this.transcripts = transcripts;
    return this;
  }

  public EarningsCallTranscriptsList addTranscriptsItem(StockTranscripts transcriptsItem) {
    if (this.transcripts == null) {
      this.transcripts = new ArrayList<StockTranscripts>();
    }
    this.transcripts.add(transcriptsItem);
    return this;
  }

   /**
   * Array of transcripts&#x27; metadata
   * @return transcripts
  **/
  @Schema(description = "Array of transcripts' metadata")
  public List<StockTranscripts> getTranscripts() {
    return transcripts;
  }

  public void setTranscripts(List<StockTranscripts> transcripts) {
    this.transcripts = transcripts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningsCallTranscriptsList earningsCallTranscriptsList = (EarningsCallTranscriptsList) o;
    return Objects.equals(this.symbol, earningsCallTranscriptsList.symbol) &&
        Objects.equals(this.transcripts, earningsCallTranscriptsList.transcripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, transcripts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningsCallTranscriptsList {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    transcripts: ").append(toIndentedString(transcripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
