/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * EarningsEstimates
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class EarningsEstimates {
  @SerializedName("data")
  private List<EarningsEstimatesInfo> data = null;

  @SerializedName("freq")
  private String freq = null;

  @SerializedName("symbol")
  private String symbol = null;

  public EarningsEstimates data(List<EarningsEstimatesInfo> data) {
    this.data = data;
    return this;
  }

  public EarningsEstimates addDataItem(EarningsEstimatesInfo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<EarningsEstimatesInfo>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * List of estimates
   * @return data
  **/
  @Schema(description = "List of estimates")
  public List<EarningsEstimatesInfo> getData() {
    return data;
  }

  public void setData(List<EarningsEstimatesInfo> data) {
    this.data = data;
  }

  public EarningsEstimates freq(String freq) {
    this.freq = freq;
    return this;
  }

   /**
   * Frequency: annual or quarterly.
   * @return freq
  **/
  @Schema(description = "Frequency: annual or quarterly.")
  public String getFreq() {
    return freq;
  }

  public void setFreq(String freq) {
    this.freq = freq;
  }

  public EarningsEstimates symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Company symbol.
   * @return symbol
  **/
  @Schema(description = "Company symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningsEstimates earningsEstimates = (EarningsEstimates) o;
    return Objects.equals(this.data, earningsEstimates.data) &&
        Objects.equals(this.freq, earningsEstimates.freq) &&
        Objects.equals(this.symbol, earningsEstimates.symbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, freq, symbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningsEstimates {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    freq: ").append(toIndentedString(freq)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
