/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * EarningsCalendar
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class EarningsCalendar {
  @SerializedName("earningsCalendar")
  private List<EarningRelease> earningsCalendar = null;

  public EarningsCalendar earningsCalendar(List<EarningRelease> earningsCalendar) {
    this.earningsCalendar = earningsCalendar;
    return this;
  }

  public EarningsCalendar addEarningsCalendarItem(EarningRelease earningsCalendarItem) {
    if (this.earningsCalendar == null) {
      this.earningsCalendar = new ArrayList<EarningRelease>();
    }
    this.earningsCalendar.add(earningsCalendarItem);
    return this;
  }

   /**
   * Array of earnings release.
   * @return earningsCalendar
  **/
  @Schema(description = "Array of earnings release.")
  public List<EarningRelease> getEarningsCalendar() {
    return earningsCalendar;
  }

  public void setEarningsCalendar(List<EarningRelease> earningsCalendar) {
    this.earningsCalendar = earningsCalendar;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningsCalendar earningsCalendar = (EarningsCalendar) o;
    return Objects.equals(this.earningsCalendar, earningsCalendar.earningsCalendar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earningsCalendar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningsCalendar {\n");
    
    sb.append("    earningsCalendar: ").append(toIndentedString(earningsCalendar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
