/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * EconomicCode
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class EconomicCode {
  @SerializedName("code")
  private String code = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("unit")
  private String unit = null;

  public EconomicCode code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Finnhub economic code used to get historical data
   * @return code
  **/
  @Schema(description = "Finnhub economic code used to get historical data")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EconomicCode country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country
   * @return country
  **/
  @Schema(description = "Country")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public EconomicCode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Indicator name
   * @return name
  **/
  @Schema(description = "Indicator name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EconomicCode unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Unit
   * @return unit
  **/
  @Schema(description = "Unit")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EconomicCode economicCode = (EconomicCode) o;
    return Objects.equals(this.code, economicCode.code) &&
        Objects.equals(this.country, economicCode.country) &&
        Objects.equals(this.name, economicCode.name) &&
        Objects.equals(this.unit, economicCode.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, country, name, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EconomicCode {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
