/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * FinancialsAsReported
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class FinancialsAsReported {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("cik")
  private String cik = null;

  @SerializedName("data")
  private List<Report> data = null;

  public FinancialsAsReported symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol
   * @return symbol
  **/
  @Schema(description = "Symbol")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public FinancialsAsReported cik(String cik) {
    this.cik = cik;
    return this;
  }

   /**
   * CIK
   * @return cik
  **/
  @Schema(description = "CIK")
  public String getCik() {
    return cik;
  }

  public void setCik(String cik) {
    this.cik = cik;
  }

  public FinancialsAsReported data(List<Report> data) {
    this.data = data;
    return this;
  }

  public FinancialsAsReported addDataItem(Report dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<Report>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Array of filings.
   * @return data
  **/
  @Schema(description = "Array of filings.")
  public List<Report> getData() {
    return data;
  }

  public void setData(List<Report> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialsAsReported financialsAsReported = (FinancialsAsReported) o;
    return Objects.equals(this.symbol, financialsAsReported.symbol) &&
        Objects.equals(this.cik, financialsAsReported.cik) &&
        Objects.equals(this.data, financialsAsReported.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, cik, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialsAsReported {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
