/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.LocalDate;

import java.util.Objects;
/**
 * FundOwnershipInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class FundOwnershipInfo {
  @SerializedName("name")
  private String name = null;

  @SerializedName("share")
  private Long share = null;

  @SerializedName("change")
  private Long change = null;

  @SerializedName("filingDate")
  private LocalDate filingDate = null;

  @SerializedName("portfolioPercent")
  private Float portfolioPercent = null;

  public FundOwnershipInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Investor&#x27;s name.
   * @return name
  **/
  @Schema(description = "Investor's name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FundOwnershipInfo share(Long share) {
    this.share = share;
    return this;
  }

   /**
   * Number of shares held by the investor.
   * @return share
  **/
  @Schema(description = "Number of shares held by the investor.")
  public Long getShare() {
    return share;
  }

  public void setShare(Long share) {
    this.share = share;
  }

  public FundOwnershipInfo change(Long change) {
    this.change = change;
    return this;
  }

   /**
   * Number of share changed (net buy or sell) from the last period.
   * @return change
  **/
  @Schema(description = "Number of share changed (net buy or sell) from the last period.")
  public Long getChange() {
    return change;
  }

  public void setChange(Long change) {
    this.change = change;
  }

  public FundOwnershipInfo filingDate(LocalDate filingDate) {
    this.filingDate = filingDate;
    return this;
  }

   /**
   * Filing date.
   * @return filingDate
  **/
  @Schema(description = "Filing date.")
  public LocalDate getFilingDate() {
    return filingDate;
  }

  public void setFilingDate(LocalDate filingDate) {
    this.filingDate = filingDate;
  }

  public FundOwnershipInfo portfolioPercent(Float portfolioPercent) {
    this.portfolioPercent = portfolioPercent;
    return this;
  }

   /**
   * Percent of the fund&#x27;s portfolio comprised of the company&#x27;s share.
   * @return portfolioPercent
  **/
  @Schema(description = "Percent of the fund's portfolio comprised of the company's share.")
  public Float getPortfolioPercent() {
    return portfolioPercent;
  }

  public void setPortfolioPercent(Float portfolioPercent) {
    this.portfolioPercent = portfolioPercent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundOwnershipInfo fundOwnershipInfo = (FundOwnershipInfo) o;
    return Objects.equals(this.name, fundOwnershipInfo.name) &&
        Objects.equals(this.share, fundOwnershipInfo.share) &&
        Objects.equals(this.change, fundOwnershipInfo.change) &&
        Objects.equals(this.filingDate, fundOwnershipInfo.filingDate) &&
        Objects.equals(this.portfolioPercent, fundOwnershipInfo.portfolioPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, share, change, filingDate, portfolioPercent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundOwnershipInfo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    share: ").append(toIndentedString(share)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    portfolioPercent: ").append(toIndentedString(portfolioPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
