/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.LocalDate;
/**
 * IndexHistoricalConstituent
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class IndexHistoricalConstituent {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("action")
  private String action = null;

  @SerializedName("date")
  private LocalDate date = null;

  public IndexHistoricalConstituent symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol
   * @return symbol
  **/
  @Schema(description = "Symbol")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public IndexHistoricalConstituent action(String action) {
    this.action = action;
    return this;
  }

   /**
   * &lt;code&gt;add&lt;/code&gt; or &lt;code&gt;remove&lt;/code&gt;.
   * @return action
  **/
  @Schema(description = "<code>add</code> or <code>remove</code>.")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public IndexHistoricalConstituent date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Date of joining or leaving the index.
   * @return date
  **/
  @Schema(description = "Date of joining or leaving the index.")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexHistoricalConstituent indexHistoricalConstituent = (IndexHistoricalConstituent) o;
    return Objects.equals(this.symbol, indexHistoricalConstituent.symbol) &&
        Objects.equals(this.action, indexHistoricalConstituent.action) &&
        Objects.equals(this.date, indexHistoricalConstituent.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, action, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexHistoricalConstituent {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
