/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InFilingSearchBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InFilingSearchBody {
  @SerializedName("query")
  private String query = null;

  @SerializedName("filingId")
  private String filingId = null;

  public InFilingSearchBody query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Search query
   * @return query
  **/
  @Schema(required = true, description = "Search query")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public InFilingSearchBody filingId(String filingId) {
    this.filingId = filingId;
    return this;
  }

   /**
   * Filing Id to search
   * @return filingId
  **/
  @Schema(required = true, description = "Filing Id to search")
  public String getFilingId() {
    return filingId;
  }

  public void setFilingId(String filingId) {
    this.filingId = filingId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InFilingSearchBody inFilingSearchBody = (InFilingSearchBody) o;
    return Objects.equals(this.query, inFilingSearchBody.query) &&
        Objects.equals(this.filingId, inFilingSearchBody.filingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, filingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InFilingSearchBody {\n");
    
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    filingId: ").append(toIndentedString(filingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
