/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * InFilingResponse
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InFilingResponse {
  @SerializedName("filingId")
  private String filingId = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("filerId")
  private String filerId = null;

  @SerializedName("symbol")
  private Object symbol = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("acceptanceDate")
  private String acceptanceDate = null;

  @SerializedName("filedDate")
  private String filedDate = null;

  @SerializedName("reportDate")
  private String reportDate = null;

  @SerializedName("form")
  private String form = null;

  @SerializedName("amend")
  private Boolean amend = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("pageCount")
  private Integer pageCount = null;

  @SerializedName("documentCount")
  private Integer documentCount = null;

  @SerializedName("documents")
  private List<DocumentResponse> documents = null;

  public InFilingResponse filingId(String filingId) {
    this.filingId = filingId;
    return this;
  }

   /**
   * Filing Id in Alpharesearch platform
   * @return filingId
  **/
  @Schema(description = "Filing Id in Alpharesearch platform")
  public String getFilingId() {
    return filingId;
  }

  public void setFilingId(String filingId) {
    this.filingId = filingId;
  }

  public InFilingResponse title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Filing title
   * @return title
  **/
  @Schema(description = "Filing title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InFilingResponse filerId(String filerId) {
    this.filerId = filerId;
    return this;
  }

   /**
   * Id of the entity submitted the filing
   * @return filerId
  **/
  @Schema(description = "Id of the entity submitted the filing")
  public String getFilerId() {
    return filerId;
  }

  public void setFilerId(String filerId) {
    this.filerId = filerId;
  }

  public InFilingResponse symbol(Object symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * List of symbol associate with this filing
   * @return symbol
  **/
  @Schema(description = "List of symbol associate with this filing")
  public Object getSymbol() {
    return symbol;
  }

  public void setSymbol(Object symbol) {
    this.symbol = symbol;
  }

  public InFilingResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Filer name
   * @return name
  **/
  @Schema(description = "Filer name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InFilingResponse acceptanceDate(String acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
    return this;
  }

   /**
   * Date the filing is submitted.
   * @return acceptanceDate
  **/
  @Schema(description = "Date the filing is submitted.")
  public String getAcceptanceDate() {
    return acceptanceDate;
  }

  public void setAcceptanceDate(String acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
  }

  public InFilingResponse filedDate(String filedDate) {
    this.filedDate = filedDate;
    return this;
  }

   /**
   * Date the filing is make available to the public
   * @return filedDate
  **/
  @Schema(description = "Date the filing is make available to the public")
  public String getFiledDate() {
    return filedDate;
  }

  public void setFiledDate(String filedDate) {
    this.filedDate = filedDate;
  }

  public InFilingResponse reportDate(String reportDate) {
    this.reportDate = reportDate;
    return this;
  }

   /**
   * Date as which the filing is reported
   * @return reportDate
  **/
  @Schema(description = "Date as which the filing is reported")
  public String getReportDate() {
    return reportDate;
  }

  public void setReportDate(String reportDate) {
    this.reportDate = reportDate;
  }

  public InFilingResponse form(String form) {
    this.form = form;
    return this;
  }

   /**
   * Filing Form
   * @return form
  **/
  @Schema(description = "Filing Form")
  public String getForm() {
    return form;
  }

  public void setForm(String form) {
    this.form = form;
  }

  public InFilingResponse amend(Boolean amend) {
    this.amend = amend;
    return this;
  }

   /**
   * Amendment
   * @return amend
  **/
  @Schema(description = "Amendment")
  public Boolean isAmend() {
    return amend;
  }

  public void setAmend(Boolean amend) {
    this.amend = amend;
  }

  public InFilingResponse source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Filing Source
   * @return source
  **/
  @Schema(description = "Filing Source")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public InFilingResponse pageCount(Integer pageCount) {
    this.pageCount = pageCount;
    return this;
  }

   /**
   * Estimate number of page when printing
   * @return pageCount
  **/
  @Schema(description = "Estimate number of page when printing")
  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public InFilingResponse documentCount(Integer documentCount) {
    this.documentCount = documentCount;
    return this;
  }

   /**
   * Number of document in this filing
   * @return documentCount
  **/
  @Schema(description = "Number of document in this filing")
  public Integer getDocumentCount() {
    return documentCount;
  }

  public void setDocumentCount(Integer documentCount) {
    this.documentCount = documentCount;
  }

  public InFilingResponse documents(List<DocumentResponse> documents) {
    this.documents = documents;
    return this;
  }

  public InFilingResponse addDocumentsItem(DocumentResponse documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<DocumentResponse>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Document for this filing.
   * @return documents
  **/
  @Schema(description = "Document for this filing.")
  public List<DocumentResponse> getDocuments() {
    return documents;
  }

  public void setDocuments(List<DocumentResponse> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InFilingResponse inFilingResponse = (InFilingResponse) o;
    return Objects.equals(this.filingId, inFilingResponse.filingId) &&
        Objects.equals(this.title, inFilingResponse.title) &&
        Objects.equals(this.filerId, inFilingResponse.filerId) &&
        Objects.equals(this.symbol, inFilingResponse.symbol) &&
        Objects.equals(this.name, inFilingResponse.name) &&
        Objects.equals(this.acceptanceDate, inFilingResponse.acceptanceDate) &&
        Objects.equals(this.filedDate, inFilingResponse.filedDate) &&
        Objects.equals(this.reportDate, inFilingResponse.reportDate) &&
        Objects.equals(this.form, inFilingResponse.form) &&
        Objects.equals(this.amend, inFilingResponse.amend) &&
        Objects.equals(this.source, inFilingResponse.source) &&
        Objects.equals(this.pageCount, inFilingResponse.pageCount) &&
        Objects.equals(this.documentCount, inFilingResponse.documentCount) &&
        Objects.equals(this.documents, inFilingResponse.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filingId, title, filerId, symbol, name, acceptanceDate, filedDate, reportDate, form, amend, source, pageCount, documentCount, documents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InFilingResponse {\n");
    
    sb.append("    filingId: ").append(toIndentedString(filingId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    filerId: ").append(toIndentedString(filerId)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    acceptanceDate: ").append(toIndentedString(acceptanceDate)).append("\n");
    sb.append("    filedDate: ").append(toIndentedString(filedDate)).append("\n");
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    amend: ").append(toIndentedString(amend)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    documentCount: ").append(toIndentedString(documentCount)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
