/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * InstitutionalOwnershipGroup
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InstitutionalOwnershipGroup {
  @SerializedName("reportDate")
  private String reportDate = null;

  @SerializedName("ownership")
  private List<InstitutionalOwnershipInfo> ownership = null;

  public InstitutionalOwnershipGroup reportDate(String reportDate) {
    this.reportDate = reportDate;
    return this;
  }

   /**
   * Report date.
   * @return reportDate
  **/
  @Schema(description = "Report date.")
  public String getReportDate() {
    return reportDate;
  }

  public void setReportDate(String reportDate) {
    this.reportDate = reportDate;
  }

  public InstitutionalOwnershipGroup ownership(List<InstitutionalOwnershipInfo> ownership) {
    this.ownership = ownership;
    return this;
  }

  public InstitutionalOwnershipGroup addOwnershipItem(InstitutionalOwnershipInfo ownershipItem) {
    if (this.ownership == null) {
      this.ownership = new ArrayList<InstitutionalOwnershipInfo>();
    }
    this.ownership.add(ownershipItem);
    return this;
  }

   /**
   * Array of institutional investors.
   * @return ownership
  **/
  @Schema(description = "Array of institutional investors.")
  public List<InstitutionalOwnershipInfo> getOwnership() {
    return ownership;
  }

  public void setOwnership(List<InstitutionalOwnershipInfo> ownership) {
    this.ownership = ownership;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstitutionalOwnershipGroup institutionalOwnershipGroup = (InstitutionalOwnershipGroup) o;
    return Objects.equals(this.reportDate, institutionalOwnershipGroup.reportDate) &&
        Objects.equals(this.ownership, institutionalOwnershipGroup.ownership);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportDate, ownership);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstitutionalOwnershipGroup {\n");
    
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    ownership: ").append(toIndentedString(ownership)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
