/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * InstitutionalProfile
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InstitutionalProfile {
  @SerializedName("cik")
  private String cik = null;

  @SerializedName("data")
  private List<InstitutionalProfileInfo> data = null;

  public InstitutionalProfile cik(String cik) {
    this.cik = cik;
    return this;
  }

   /**
   * CIK.
   * @return cik
  **/
  @Schema(description = "CIK.")
  public String getCik() {
    return cik;
  }

  public void setCik(String cik) {
    this.cik = cik;
  }

  public InstitutionalProfile data(List<InstitutionalProfileInfo> data) {
    this.data = data;
    return this;
  }

  public InstitutionalProfile addDataItem(InstitutionalProfileInfo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<InstitutionalProfileInfo>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Array of investors.
   * @return data
  **/
  @Schema(description = "Array of investors.")
  public List<InstitutionalProfileInfo> getData() {
    return data;
  }

  public void setData(List<InstitutionalProfileInfo> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstitutionalProfile institutionalProfile = (InstitutionalProfile) o;
    return Objects.equals(this.cik, institutionalProfile.cik) &&
        Objects.equals(this.data, institutionalProfile.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cik, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstitutionalProfile {\n");
    
    sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
