/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * InstitutionalPortfolioGroup
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class InstitutionalPortfolioGroup {
  @SerializedName("reportDate")
  private String reportDate = null;

  @SerializedName("filingDate")
  private String filingDate = null;

  @SerializedName("portfolio")
  private List<InstitutionalPortfolioInfo> portfolio = null;

  public InstitutionalPortfolioGroup reportDate(String reportDate) {
    this.reportDate = reportDate;
    return this;
  }

   /**
   * Report date.
   * @return reportDate
  **/
  @Schema(description = "Report date.")
  public String getReportDate() {
    return reportDate;
  }

  public void setReportDate(String reportDate) {
    this.reportDate = reportDate;
  }

  public InstitutionalPortfolioGroup filingDate(String filingDate) {
    this.filingDate = filingDate;
    return this;
  }

   /**
   * Filing date.
   * @return filingDate
  **/
  @Schema(description = "Filing date.")
  public String getFilingDate() {
    return filingDate;
  }

  public void setFilingDate(String filingDate) {
    this.filingDate = filingDate;
  }

  public InstitutionalPortfolioGroup portfolio(List<InstitutionalPortfolioInfo> portfolio) {
    this.portfolio = portfolio;
    return this;
  }

  public InstitutionalPortfolioGroup addPortfolioItem(InstitutionalPortfolioInfo portfolioItem) {
    if (this.portfolio == null) {
      this.portfolio = new ArrayList<InstitutionalPortfolioInfo>();
    }
    this.portfolio.add(portfolioItem);
    return this;
  }

   /**
   * Array of positions.
   * @return portfolio
  **/
  @Schema(description = "Array of positions.")
  public List<InstitutionalPortfolioInfo> getPortfolio() {
    return portfolio;
  }

  public void setPortfolio(List<InstitutionalPortfolioInfo> portfolio) {
    this.portfolio = portfolio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstitutionalPortfolioGroup institutionalPortfolioGroup = (InstitutionalPortfolioGroup) o;
    return Objects.equals(this.reportDate, institutionalPortfolioGroup.reportDate) &&
        Objects.equals(this.filingDate, institutionalPortfolioGroup.filingDate) &&
        Objects.equals(this.portfolio, institutionalPortfolioGroup.portfolio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportDate, filingDate, portfolio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstitutionalPortfolioGroup {\n");
    
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    portfolio: ").append(toIndentedString(portfolio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
