/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * IsinChange
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class IsinChange {
  @SerializedName("fromDate")
  private String fromDate = null;

  @SerializedName("toDate")
  private String toDate = null;

  @SerializedName("data")
  private List<IsinChangeInfo> data = null;

  public IsinChange fromDate(String fromDate) {
    this.fromDate = fromDate;
    return this;
  }

   /**
   * From date.
   * @return fromDate
  **/
  @Schema(description = "From date.")
  public String getFromDate() {
    return fromDate;
  }

  public void setFromDate(String fromDate) {
    this.fromDate = fromDate;
  }

  public IsinChange toDate(String toDate) {
    this.toDate = toDate;
    return this;
  }

   /**
   * To date.
   * @return toDate
  **/
  @Schema(description = "To date.")
  public String getToDate() {
    return toDate;
  }

  public void setToDate(String toDate) {
    this.toDate = toDate;
  }

  public IsinChange data(List<IsinChangeInfo> data) {
    this.data = data;
    return this;
  }

  public IsinChange addDataItem(IsinChangeInfo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<IsinChangeInfo>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Array of ISIN change events.
   * @return data
  **/
  @Schema(description = "Array of ISIN change events.")
  public List<IsinChangeInfo> getData() {
    return data;
  }

  public void setData(List<IsinChangeInfo> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IsinChange isinChange = (IsinChange) o;
    return Objects.equals(this.fromDate, isinChange.fromDate) &&
        Objects.equals(this.toDate, isinChange.toDate) &&
        Objects.equals(this.data, isinChange.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromDate, toDate, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IsinChange {\n");
    
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
