/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * LobbyingData
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class LobbyingData {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("year")
  private Long year = null;

  @SerializedName("period")
  private String period = null;

  @SerializedName("income")
  private Float income = null;

  @SerializedName("expenses")
  private Float expenses = null;

  @SerializedName("documentUrl")
  private String documentUrl = null;

  @SerializedName("postedName")
  private String postedName = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("registrantId")
  private String registrantId = null;

  @SerializedName("senateId")
  private String senateId = null;

  @SerializedName("houseregistrantId")
  private String houseregistrantId = null;

  public LobbyingData symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol.
   * @return symbol
  **/
  @Schema(description = "Symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public LobbyingData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Company&#x27;s name.
   * @return name
  **/
  @Schema(description = "Company's name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LobbyingData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description.
   * @return description
  **/
  @Schema(description = "Description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LobbyingData country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country.
   * @return country
  **/
  @Schema(description = "Country.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public LobbyingData year(Long year) {
    this.year = year;
    return this;
  }

   /**
   * Year.
   * @return year
  **/
  @Schema(description = "Year.")
  public Long getYear() {
    return year;
  }

  public void setYear(Long year) {
    this.year = year;
  }

  public LobbyingData period(String period) {
    this.period = period;
    return this;
  }

   /**
   * Period.
   * @return period
  **/
  @Schema(description = "Period.")
  public String getPeriod() {
    return period;
  }

  public void setPeriod(String period) {
    this.period = period;
  }

  public LobbyingData income(Float income) {
    this.income = income;
    return this;
  }

   /**
   * Income reported by lobbying firms.
   * @return income
  **/
  @Schema(description = "Income reported by lobbying firms.")
  public Float getIncome() {
    return income;
  }

  public void setIncome(Float income) {
    this.income = income;
  }

  public LobbyingData expenses(Float expenses) {
    this.expenses = expenses;
    return this;
  }

   /**
   * Expenses reported by the company.
   * @return expenses
  **/
  @Schema(description = "Expenses reported by the company.")
  public Float getExpenses() {
    return expenses;
  }

  public void setExpenses(Float expenses) {
    this.expenses = expenses;
  }

  public LobbyingData documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * Document&#x27;s URL.
   * @return documentUrl
  **/
  @Schema(description = "Document's URL.")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public LobbyingData postedName(String postedName) {
    this.postedName = postedName;
    return this;
  }

   /**
   * Posted name.
   * @return postedName
  **/
  @Schema(description = "Posted name.")
  public String getPostedName() {
    return postedName;
  }

  public void setPostedName(String postedName) {
    this.postedName = postedName;
  }

  public LobbyingData date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Date.
   * @return date
  **/
  @Schema(description = "Date.")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public LobbyingData clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Client ID.
   * @return clientId
  **/
  @Schema(description = "Client ID.")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public LobbyingData registrantId(String registrantId) {
    this.registrantId = registrantId;
    return this;
  }

   /**
   * Registrant ID.
   * @return registrantId
  **/
  @Schema(description = "Registrant ID.")
  public String getRegistrantId() {
    return registrantId;
  }

  public void setRegistrantId(String registrantId) {
    this.registrantId = registrantId;
  }

  public LobbyingData senateId(String senateId) {
    this.senateId = senateId;
    return this;
  }

   /**
   * Senate ID.
   * @return senateId
  **/
  @Schema(description = "Senate ID.")
  public String getSenateId() {
    return senateId;
  }

  public void setSenateId(String senateId) {
    this.senateId = senateId;
  }

  public LobbyingData houseregistrantId(String houseregistrantId) {
    this.houseregistrantId = houseregistrantId;
    return this;
  }

   /**
   * House registrant ID.
   * @return houseregistrantId
  **/
  @Schema(description = "House registrant ID.")
  public String getHouseregistrantId() {
    return houseregistrantId;
  }

  public void setHouseregistrantId(String houseregistrantId) {
    this.houseregistrantId = houseregistrantId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LobbyingData lobbyingData = (LobbyingData) o;
    return Objects.equals(this.symbol, lobbyingData.symbol) &&
        Objects.equals(this.name, lobbyingData.name) &&
        Objects.equals(this.description, lobbyingData.description) &&
        Objects.equals(this.country, lobbyingData.country) &&
        Objects.equals(this.year, lobbyingData.year) &&
        Objects.equals(this.period, lobbyingData.period) &&
        Objects.equals(this.income, lobbyingData.income) &&
        Objects.equals(this.expenses, lobbyingData.expenses) &&
        Objects.equals(this.documentUrl, lobbyingData.documentUrl) &&
        Objects.equals(this.postedName, lobbyingData.postedName) &&
        Objects.equals(this.date, lobbyingData.date) &&
        Objects.equals(this.clientId, lobbyingData.clientId) &&
        Objects.equals(this.registrantId, lobbyingData.registrantId) &&
        Objects.equals(this.senateId, lobbyingData.senateId) &&
        Objects.equals(this.houseregistrantId, lobbyingData.houseregistrantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, name, description, country, year, period, income, expenses, documentUrl, postedName, date, clientId, registrantId, senateId, houseregistrantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LobbyingData {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    expenses: ").append(toIndentedString(expenses)).append("\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    postedName: ").append(toIndentedString(postedName)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    registrantId: ").append(toIndentedString(registrantId)).append("\n");
    sb.append("    senateId: ").append(toIndentedString(senateId)).append("\n");
    sb.append("    houseregistrantId: ").append(toIndentedString(houseregistrantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
