/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * PriceMetrics
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class PriceMetrics {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("atDate")
  private String atDate = null;

  @SerializedName("data")
  private PriceMetricMap data = null;

  public PriceMetrics symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol of the company.
   * @return symbol
  **/
  @Schema(description = "Symbol of the company.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public PriceMetrics atDate(String atDate) {
    this.atDate = atDate;
    return this;
  }

   /**
   * Data date.
   * @return atDate
  **/
  @Schema(description = "Data date.")
  public String getAtDate() {
    return atDate;
  }

  public void setAtDate(String atDate) {
    this.atDate = atDate;
  }

  public PriceMetrics data(PriceMetricMap data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public PriceMetricMap getData() {
    return data;
  }

  public void setData(PriceMetricMap data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceMetrics priceMetrics = (PriceMetrics) o;
    return Objects.equals(this.symbol, priceMetrics.symbol) &&
        Objects.equals(this.atDate, priceMetrics.atDate) &&
        Objects.equals(this.data, priceMetrics.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, atDate, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceMetrics {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    atDate: ").append(toIndentedString(atDate)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
