/*
 * Finnhub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.oscerd.finnhub.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * UsaSpending
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-22T10:38:13.551248835+01:00[Europe/Rome]")

public class UsaSpending {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("recipientName")
  private String recipientName = null;

  @SerializedName("recipientParentName")
  private String recipientParentName = null;

  @SerializedName("awardDescription")
  private String awardDescription = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("actionDate")
  private String actionDate = null;

  @SerializedName("totalValue")
  private Float totalValue = null;

  @SerializedName("performanceStartDate")
  private String performanceStartDate = null;

  @SerializedName("performanceEndDate")
  private String performanceEndDate = null;

  @SerializedName("awardingAgencyName")
  private String awardingAgencyName = null;

  @SerializedName("awardingSubAgencyName")
  private String awardingSubAgencyName = null;

  @SerializedName("awardingOfficeName")
  private String awardingOfficeName = null;

  @SerializedName("performanceCountry")
  private String performanceCountry = null;

  @SerializedName("performanceCity")
  private String performanceCity = null;

  @SerializedName("performanceCounty")
  private String performanceCounty = null;

  @SerializedName("performanceState")
  private String performanceState = null;

  @SerializedName("performanceZipCode")
  private String performanceZipCode = null;

  @SerializedName("performanceCongressionalDistrict")
  private String performanceCongressionalDistrict = null;

  @SerializedName("naicsCode")
  private String naicsCode = null;

  @SerializedName("permalink")
  private String permalink = null;

  public UsaSpending symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol.
   * @return symbol
  **/
  @Schema(description = "Symbol.")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public UsaSpending recipientName(String recipientName) {
    this.recipientName = recipientName;
    return this;
  }

   /**
   * Company&#x27;s name.
   * @return recipientName
  **/
  @Schema(description = "Company's name.")
  public String getRecipientName() {
    return recipientName;
  }

  public void setRecipientName(String recipientName) {
    this.recipientName = recipientName;
  }

  public UsaSpending recipientParentName(String recipientParentName) {
    this.recipientParentName = recipientParentName;
    return this;
  }

   /**
   * Company&#x27;s name.
   * @return recipientParentName
  **/
  @Schema(description = "Company's name.")
  public String getRecipientParentName() {
    return recipientParentName;
  }

  public void setRecipientParentName(String recipientParentName) {
    this.recipientParentName = recipientParentName;
  }

  public UsaSpending awardDescription(String awardDescription) {
    this.awardDescription = awardDescription;
    return this;
  }

   /**
   * Description.
   * @return awardDescription
  **/
  @Schema(description = "Description.")
  public String getAwardDescription() {
    return awardDescription;
  }

  public void setAwardDescription(String awardDescription) {
    this.awardDescription = awardDescription;
  }

  public UsaSpending country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Recipient&#x27;s country.
   * @return country
  **/
  @Schema(description = "Recipient's country.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public UsaSpending actionDate(String actionDate) {
    this.actionDate = actionDate;
    return this;
  }

   /**
   * Period.
   * @return actionDate
  **/
  @Schema(description = "Period.")
  public String getActionDate() {
    return actionDate;
  }

  public void setActionDate(String actionDate) {
    this.actionDate = actionDate;
  }

  public UsaSpending totalValue(Float totalValue) {
    this.totalValue = totalValue;
    return this;
  }

   /**
   * Income reported by lobbying firms.
   * @return totalValue
  **/
  @Schema(description = "Income reported by lobbying firms.")
  public Float getTotalValue() {
    return totalValue;
  }

  public void setTotalValue(Float totalValue) {
    this.totalValue = totalValue;
  }

  public UsaSpending performanceStartDate(String performanceStartDate) {
    this.performanceStartDate = performanceStartDate;
    return this;
  }

   /**
   * Performance start date.
   * @return performanceStartDate
  **/
  @Schema(description = "Performance start date.")
  public String getPerformanceStartDate() {
    return performanceStartDate;
  }

  public void setPerformanceStartDate(String performanceStartDate) {
    this.performanceStartDate = performanceStartDate;
  }

  public UsaSpending performanceEndDate(String performanceEndDate) {
    this.performanceEndDate = performanceEndDate;
    return this;
  }

   /**
   * Performance end date.
   * @return performanceEndDate
  **/
  @Schema(description = "Performance end date.")
  public String getPerformanceEndDate() {
    return performanceEndDate;
  }

  public void setPerformanceEndDate(String performanceEndDate) {
    this.performanceEndDate = performanceEndDate;
  }

  public UsaSpending awardingAgencyName(String awardingAgencyName) {
    this.awardingAgencyName = awardingAgencyName;
    return this;
  }

   /**
   * Award agency.
   * @return awardingAgencyName
  **/
  @Schema(description = "Award agency.")
  public String getAwardingAgencyName() {
    return awardingAgencyName;
  }

  public void setAwardingAgencyName(String awardingAgencyName) {
    this.awardingAgencyName = awardingAgencyName;
  }

  public UsaSpending awardingSubAgencyName(String awardingSubAgencyName) {
    this.awardingSubAgencyName = awardingSubAgencyName;
    return this;
  }

   /**
   * Award sub-agency.
   * @return awardingSubAgencyName
  **/
  @Schema(description = "Award sub-agency.")
  public String getAwardingSubAgencyName() {
    return awardingSubAgencyName;
  }

  public void setAwardingSubAgencyName(String awardingSubAgencyName) {
    this.awardingSubAgencyName = awardingSubAgencyName;
  }

  public UsaSpending awardingOfficeName(String awardingOfficeName) {
    this.awardingOfficeName = awardingOfficeName;
    return this;
  }

   /**
   * Award office name.
   * @return awardingOfficeName
  **/
  @Schema(description = "Award office name.")
  public String getAwardingOfficeName() {
    return awardingOfficeName;
  }

  public void setAwardingOfficeName(String awardingOfficeName) {
    this.awardingOfficeName = awardingOfficeName;
  }

  public UsaSpending performanceCountry(String performanceCountry) {
    this.performanceCountry = performanceCountry;
    return this;
  }

   /**
   * Performance country.
   * @return performanceCountry
  **/
  @Schema(description = "Performance country.")
  public String getPerformanceCountry() {
    return performanceCountry;
  }

  public void setPerformanceCountry(String performanceCountry) {
    this.performanceCountry = performanceCountry;
  }

  public UsaSpending performanceCity(String performanceCity) {
    this.performanceCity = performanceCity;
    return this;
  }

   /**
   * Performance city.
   * @return performanceCity
  **/
  @Schema(description = "Performance city.")
  public String getPerformanceCity() {
    return performanceCity;
  }

  public void setPerformanceCity(String performanceCity) {
    this.performanceCity = performanceCity;
  }

  public UsaSpending performanceCounty(String performanceCounty) {
    this.performanceCounty = performanceCounty;
    return this;
  }

   /**
   * Performance county.
   * @return performanceCounty
  **/
  @Schema(description = "Performance county.")
  public String getPerformanceCounty() {
    return performanceCounty;
  }

  public void setPerformanceCounty(String performanceCounty) {
    this.performanceCounty = performanceCounty;
  }

  public UsaSpending performanceState(String performanceState) {
    this.performanceState = performanceState;
    return this;
  }

   /**
   * Performance state.
   * @return performanceState
  **/
  @Schema(description = "Performance state.")
  public String getPerformanceState() {
    return performanceState;
  }

  public void setPerformanceState(String performanceState) {
    this.performanceState = performanceState;
  }

  public UsaSpending performanceZipCode(String performanceZipCode) {
    this.performanceZipCode = performanceZipCode;
    return this;
  }

   /**
   * Performance zip code.
   * @return performanceZipCode
  **/
  @Schema(description = "Performance zip code.")
  public String getPerformanceZipCode() {
    return performanceZipCode;
  }

  public void setPerformanceZipCode(String performanceZipCode) {
    this.performanceZipCode = performanceZipCode;
  }

  public UsaSpending performanceCongressionalDistrict(String performanceCongressionalDistrict) {
    this.performanceCongressionalDistrict = performanceCongressionalDistrict;
    return this;
  }

   /**
   * Performance congressional district.
   * @return performanceCongressionalDistrict
  **/
  @Schema(description = "Performance congressional district.")
  public String getPerformanceCongressionalDistrict() {
    return performanceCongressionalDistrict;
  }

  public void setPerformanceCongressionalDistrict(String performanceCongressionalDistrict) {
    this.performanceCongressionalDistrict = performanceCongressionalDistrict;
  }

  public UsaSpending naicsCode(String naicsCode) {
    this.naicsCode = naicsCode;
    return this;
  }

   /**
   * NAICS code.
   * @return naicsCode
  **/
  @Schema(description = "NAICS code.")
  public String getNaicsCode() {
    return naicsCode;
  }

  public void setNaicsCode(String naicsCode) {
    this.naicsCode = naicsCode;
  }

  public UsaSpending permalink(String permalink) {
    this.permalink = permalink;
    return this;
  }

   /**
   * Permalink.
   * @return permalink
  **/
  @Schema(description = "Permalink.")
  public String getPermalink() {
    return permalink;
  }

  public void setPermalink(String permalink) {
    this.permalink = permalink;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsaSpending usaSpending = (UsaSpending) o;
    return Objects.equals(this.symbol, usaSpending.symbol) &&
        Objects.equals(this.recipientName, usaSpending.recipientName) &&
        Objects.equals(this.recipientParentName, usaSpending.recipientParentName) &&
        Objects.equals(this.awardDescription, usaSpending.awardDescription) &&
        Objects.equals(this.country, usaSpending.country) &&
        Objects.equals(this.actionDate, usaSpending.actionDate) &&
        Objects.equals(this.totalValue, usaSpending.totalValue) &&
        Objects.equals(this.performanceStartDate, usaSpending.performanceStartDate) &&
        Objects.equals(this.performanceEndDate, usaSpending.performanceEndDate) &&
        Objects.equals(this.awardingAgencyName, usaSpending.awardingAgencyName) &&
        Objects.equals(this.awardingSubAgencyName, usaSpending.awardingSubAgencyName) &&
        Objects.equals(this.awardingOfficeName, usaSpending.awardingOfficeName) &&
        Objects.equals(this.performanceCountry, usaSpending.performanceCountry) &&
        Objects.equals(this.performanceCity, usaSpending.performanceCity) &&
        Objects.equals(this.performanceCounty, usaSpending.performanceCounty) &&
        Objects.equals(this.performanceState, usaSpending.performanceState) &&
        Objects.equals(this.performanceZipCode, usaSpending.performanceZipCode) &&
        Objects.equals(this.performanceCongressionalDistrict, usaSpending.performanceCongressionalDistrict) &&
        Objects.equals(this.naicsCode, usaSpending.naicsCode) &&
        Objects.equals(this.permalink, usaSpending.permalink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, recipientName, recipientParentName, awardDescription, country, actionDate, totalValue, performanceStartDate, performanceEndDate, awardingAgencyName, awardingSubAgencyName, awardingOfficeName, performanceCountry, performanceCity, performanceCounty, performanceState, performanceZipCode, performanceCongressionalDistrict, naicsCode, permalink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsaSpending {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    recipientName: ").append(toIndentedString(recipientName)).append("\n");
    sb.append("    recipientParentName: ").append(toIndentedString(recipientParentName)).append("\n");
    sb.append("    awardDescription: ").append(toIndentedString(awardDescription)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    actionDate: ").append(toIndentedString(actionDate)).append("\n");
    sb.append("    totalValue: ").append(toIndentedString(totalValue)).append("\n");
    sb.append("    performanceStartDate: ").append(toIndentedString(performanceStartDate)).append("\n");
    sb.append("    performanceEndDate: ").append(toIndentedString(performanceEndDate)).append("\n");
    sb.append("    awardingAgencyName: ").append(toIndentedString(awardingAgencyName)).append("\n");
    sb.append("    awardingSubAgencyName: ").append(toIndentedString(awardingSubAgencyName)).append("\n");
    sb.append("    awardingOfficeName: ").append(toIndentedString(awardingOfficeName)).append("\n");
    sb.append("    performanceCountry: ").append(toIndentedString(performanceCountry)).append("\n");
    sb.append("    performanceCity: ").append(toIndentedString(performanceCity)).append("\n");
    sb.append("    performanceCounty: ").append(toIndentedString(performanceCounty)).append("\n");
    sb.append("    performanceState: ").append(toIndentedString(performanceState)).append("\n");
    sb.append("    performanceZipCode: ").append(toIndentedString(performanceZipCode)).append("\n");
    sb.append("    performanceCongressionalDistrict: ").append(toIndentedString(performanceCongressionalDistrict)).append("\n");
    sb.append("    naicsCode: ").append(toIndentedString(naicsCode)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
